Use Github App for authentication
Gusto/apollo-federation-ruby pull request #216
Opened 2023-01-06 20:56 UTC by ethankhall

The new script will create an `INSTALLATION_ACCESS_TOKEN` scoped to this repo, and only valid for 1 hour.

This will allow the semantic version step to no longer require a human's identity.

2023-01-06 21:01 UTC, grxy requested changes
Can you add comments to the script explaining what is going on?

2023-01-10 18:46 UTC, ethankhall commented
Yes! Sorry for the delay.

2023-01-11 15:37 UTC, grxy reviewed
Everything else looks good. Will approve after a couple small typos are fixed.

2023-01-11 15:37 UTC, grxy commented on .circleci/create_release.sh
> +## Finally geneate the token from the Installation ID that is scopped to juse the repo
Typo: `juse` => `just`

2023-01-11 15:37 UTC, grxy commented on .circleci/create_release.sh
> +## Exec into semmantic release w/ GH_TOKEN set
Typo: `semmantic` => `semantic`

2023-03-08 17:41 UTC, grxy approved these changes

2023-03-08 17:44 UTC, merged

2023-03-08 17:50 UTC, grxy commented
:tada: This PR is included in version 3.5.2 :tada:

The release is available on:
- `v3.5.2`
- [GitHub release](https://github.com/Gusto/apollo-federation-ruby/releases/tag/v3.5.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: