fix: visibility checks should handle duplicate types and fields
Gusto/apollo-federation-ruby pull request #245
Opened 2023-05-19 20:38 UTC by jturkel

This PR fixes two visibility scenarios that graphql-ruby supports but apollo-federation-ruby's does not:

1. Multiple object types with the same name as long as only one is visible at runtime
2. Multiple fields with the same name as long as only one is visible at runtime

The first scenario was broken because visibility checking in [GraphQL::Schema.types](https://github.com/rmosolgo/graphql-ruby/blob/3a548f8cb540f16f09506bde9fc0778d3eba276d/lib/graphql/schema.rb#L286) was applied when generating the `_Entity` union but we don't have a properly setup context at this point, resulting in either a `GraphQL::Schema::DuplicateNamesError` or a `NoMethodError: undefined method 'introspection?' for nil:NilClass` depending on how an application has setup their visibility checks for types with the same name. The fix is to avoid any visibility checks when generating the `_Entity` union and leave it up to the graphql-ruby runtime to apply visibility checks during query execution when we have a proper context.

The second scenario was broken because the federation SDL generation was looking at all of a type's fields rather than just its visible fields resulting in `GraphQL::Schema::DuplicateNamesError`. The fix is to use warden to only look at the visible fields.

2023-05-19 20:41 UTC, jturkel commented
🤔 Looks like there's a problem with my unit tests in graphql-ruby <= 1.12. Investigating...

2023-05-19 21:09 UTC, jturkel commented
It looks like graphql-ruby added support for these scenarios in [1.13.0](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#1130-24-november-2021) so I updated the unit test to only target 1.13.0+.

2023-05-23 15:34 UTC, grxy requested changes
Requesting one additional test.

2023-05-23 15:34 UTC, grxy commented on spec/apollo-federation/service_field_v2_spec.rb
> +        it 'applies visibility checks during SDL generation' do
Can you add a test for `context[:graph_type] == :admin` as well?

2023-05-23 16:03 UTC, grxy approved these changes

2023-05-23 16:03 UTC, merged

2023-05-23 16:05 UTC, grxy commented
:tada: This PR is included in version 3.6.9 :tada:

The release is available on:
- `v3.6.9`
- [GitHub release](https://github.com/Gusto/apollo-federation-ruby/releases/tag/v3.6.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: