graphql-ruby 2.3 compatibility
Gusto/apollo-federation-ruby pull request #282
Opened 2024-09-10 09:44 UTC by Bajena

requires merging https://github.com/Gusto/apollo-federation-ruby/issues/276 first

fixes https://github.com/Gusto/apollo-federation-ruby/issues/276

This PR:
- Adds a new appraisal for `graphql-ruby 2.3`
- Adjusts the `Tracer` method to support the new way of module-based tracing (https://graphql-ruby.org/queries/tracing)
- Adjusts integration tests to use `trace_with` method in federated services
- Changes documentation to inform about the new way of tracing
- Adjusts schema generator to work with newer graphql-ruby versions (>2.3.8). It was breaking due to the lack of `warden` method.

2024-10-14 16:05 UTC, such commented
When can we expect this to be merged?

2024-12-06 06:50 UTC, risacan commented
@sethc2 could you please merge this? 🙏 or delegate to another maintainer? Thanks in advance.

2024-12-06 19:43 UTC, sethc2 requested changes
Everything looks good but because we utilize dependabot I think we generally prefer if we keep the Gemfile.lock. We follow Bundler's guidance [here](https://bundler.io/guides/faq.html#:~:text=A%3A%20Yes%2C%20you%20should%20commit,set%20of%20dependencies%20every%20time.)

Would you be opposed to adding the gemfile.lock(s) back in? We have been doing very little maintenance on this repository for the past couple years (see discussion [here](https://github.com/Gusto/apollo-federation-ruby/discussions/280)), and want to avoid any accidental breaking changes in dependencies.

2025-02-18 16:04 UTC, joeljunstrom commented
@Bajena nice! Reasonable to not delete the Gemfile.lock though? Would be very nice to get this in. Can we help?

2025-03-13 14:50 UTC, la-jamesh commented
How are we doing on this PR? This is a major issue for my teams due to #276

2025-03-15 07:30 UTC, vaclavbohac commented
Hello, thx for the feedback. We'll fix the conflicts and put back the `Gemfile.lock` back in the following week. So we can get this merged upstream.

2025-03-31 17:44 UTC, whitethunder commented
Would love to see this get merged! Thanks for addressing this issue.

2025-04-02 00:03 UTC, sethc2 approved these changes
Looks good.

2025-04-02 00:03 UTC, merged

2025-04-02 01:18 UTC, grxy commented
:tada: This PR is included in version 3.10.1 :tada:

The release is available on:
- `v3.10.1`
- [GitHub release](https://github.com/Gusto/apollo-federation-ruby/releases/tag/v3.10.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2025-04-02 01:20 UTC, sethc2 commented
I should've released this as 3.11.0 probably. If any strong opinions I can do so.