Fix context passed to GraphQL::Schema.federation_sdl
Gusto/apollo-federation-ruby pull request #95
Opened 2020-08-28 14:59 UTC by jturkel

This fixes a problem where `ApolloFederation::ServiceField#_service` passed a `context` of type `GraphQL::Query::Context` rather than `Hash` which violates the contract of [GraphQL::Language::DocumentFromSchemaDefinition#initialize](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/document_from_schema_definition.rb#L9). The API of `GraphQL::Query::Context` and `Hash` are similar enough that this didn't cause any problems until graphql-ruby 1.9.17 with the introduction of [context scoping](https://github.com/rmosolgo/graphql-ruby/pull/2634). After that change, calling `to_h`, `fetch` or `dig` on the context from anywhere in the resolution of `ApolloFederation::ServiceField#_service` (e.g. schema visibility checks) would result in a ` NoMethodError: undefined method `merge' for #<Query::Context ...>`.

2020-09-22 23:16 UTC, rylanc requested changes
This looks great! Could you rebase/merge with master so the graphql-1.11 CI checks are run?

2020-09-23 12:47 UTC, jturkel commented
@rylanc - I rebased on top of master and the tests are passing.

2020-09-30 22:07 UTC, jturkel commented
@rylanc - Looks like another merge conflict snuck in so I rebased the PR.

2020-10-29 17:30 UTC, rylanc approved these changes

2020-10-29 17:31 UTC, merged

2020-10-29 17:35 UTC, rylanc commented
:tada: This PR is included in version 1.1.5 :tada:

The release is available on:
- `v1.1.5`
- [GitHub release](https://github.com/Gusto/apollo-federation-ruby/releases/tag/v1.1.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: